# Novembre 2024 {.unnumbered}

## `[2024-11-13]`

**Objectifs**

- attaque `shomen uchi`
- `shomen uchi` suite à `ai hanmi katate dori`

**Pratique**

- [x] **salut et échauffement**

- [ ] **courir en rond : un peu de cardio**

::: {.callout-tip title="cardio" collapse="true"}
courir en rond : 

- changements de direction
- flexion au "top" : x1 x2 x3
- pas chassés : intérieurs puis extérieurs
- talons-fesses
- marcher tranquillement
- shin kokyū
:::

- [x] **henka / tenkan / tai sabaki**

- [x] **apprentissage de la chute arrière & chute avant (tapis)**

- [ ] **qu'a-t-on fait mercredi dernier et/ou samedi dernier ?**

::: {.callout-tip title="rappel" collapse="true"}
- cours de Patrice mercredi dernier
- cours de ? samedi dernier
:::

_**Attaque `Shomen Uchi` (directe)**_

- [x] **Attaque `shomen uchi`**

::: {.callout-tip title="consignes" collapse="true"}
- uke et tori pied droit devant (puis inverser)
  - vérifier la distance
- uke lève sa main droite au dessus de sa tête
- uke fait un pas chassé avec son pied avant et em même temps lance sa frappe
  - la main doit s'arrêter juste au dessus de la tête de tori
:::


- [x] **ikkyo omote**

::: {.callout-tip title="consignes" collapse="true"}
- uke attaque en `shomen`
- tori se déplace vers l'intérieur bras avant levé
  - contrôle du bras sans saisir
- tori vient saisir le coude de uke en pince 
- tori avance sa jambe arrière
- tori finit ikkyo
  - descendre le bras
  - avancer dans le déséquilibre
  - immobilisation
:::

- [x] **ikkyo ura**

::: {.callout-tip title="consignes" collapse="true"}
- uke attaque en `shomen`
- tori se décale légèrement vers l'extérieur bras levé (pied arrière)
  - contrôle du bras sans saisir
- tori vient saisir le coude de uke en pince en avançant sa jambe arrière (irimi)
- tori fait henka
- tori fait tenkan
- tori finit l'immobilisation
:::

- [x] **irimi nage (direct)**

::: {.callout-tip title="consignes" collapse="true"}
- uke attaque en `shomen`
- tori se décale légèrement vers l'extérieur bras levé (pied arrière)
  - contrôle du bras sans saisir
- tori vient saisir le cou de uke  en avançant sa jambe arrière loin derrière uke (irimi)
  - tori doit voir le dos de uke
  - tête de uke sur l'épaule de tori
- tori laisse tomber le bras qui contrôle le bras de uke, remonte son bras vers le côté de la tête de uke 
- tori avance en irimi et laisse tomber son bras
  - tori ne lache pas la tête de uke (ou fait glisser sa main dans son dos)
- tori finit l'immobilisation
:::

- [x] **kote gaeshi** 

::: {.callout-tip title="consignes" collapse="true"}
- uke attaque en `shomen`
- tori lève le bras avant pour contrôler l'attaque et sort à 90°
- tori fait un changement de hanmi et avec la main libre descend sur le poignet d'uke
- tori finit kote gaeshi en faisant un irimi derrière uke et en descendant les mains à son pied avant
- uke fait une chutte arrière
:::

- [x] **kokyu ho | étirements | respiration | relaxation**

- [x] **salut**

**Présents** : Mathis, Paul et Loup-Gaspard

{{< pagebreak >}}

## `[2024-11-20]`

**Objectifs**

- attaque `shomen uchi`
- Compléter avec 2 techniques sur attaque `shomen uchi`

**Pratique**

- [ ] **salut et échauffement**

- [ ] **courir en rond : un peu de cardio**

::: {.callout-tip title="cardio" collapse="true"}
courir en rond : 

- changements de direction
- flexion au "top" : x1 x2 x3
- pas chassés : intérieurs puis extérieurs
- talons-fesses
- marcher tranquillement
- shin kokyū
:::

- [ ] **henka / tenkan / tai sabaki**

- [ ] **apprentissage de la chute arrière & chute avant (tapis)**

- [ ] **qu'a-t-on fait mercredi dernier ?**

::: {.callout-tip title="rappel" collapse="true"}
- attaque shomen uchi
  - ikkyo omote et ura
  - irimi nage
:::

- [ ] **Faire ces 3 techniques, deux fois**

_**Attaque `Shomen Uchi` (directe)**_

- [ ] **sokomen irimi nage**

::: {.callout-tip title="consignes" collapse="true"}
- uke attaque en `shomen`
- tori lève son bras de devant en protection
  - et avance sa jambe/pied arrière au niveau de son pied avant
- tori baisse son bras (uke garde le contact)
   - et pivote à 90°, la jambe extérieure recule
  - tori place sa main extérieure dans le coude de uke
    - la main qui était en contrôle descend contrôler le poignet de uke
  - tori lève son bras devant lui (centrage)
  - tori pivote ses hanches vers uke, place sa jambe devant uke et déploie son bras vers la tête de uke
  - tori engage sa jambe derrière uke
  - uke fait une chute arrière
:::

- [ ] **kaiten nage**

::: {.callout-tip title="consignes" collapse="true"}
- uke attaque en `shomen`
- tori lève son bras de devant en protection
- tori fait irimi à l'extérieur
- tori, avec sa main extérieure vient sur le coude de uke, 
  - et en parallèle
    - descend très bas le bras de uke, tire le bras vers l'arrière et prend son poignet
    - pose sa main te-gatana sur le cou de uke et appuie pour le faire descendre
- tori engage sa jambre arrière et lève le bras de uke (cercle)
- uke fait une chute avant
:::

- [ ] **Jyu waza sur shomen uchi** 

::: {.callout-tip title="consignes" collapse="true"}
- les techniques vues
- changer toutes les 4 techniques
:::

- [ ] **kokyu ho | étirements | respiration | relaxation**

- [ ] **salut**

**Présents** : TBD

{{< pagebreak >}}

