# Décembre 2024 {.unnumbered}

## `[2024-12-04]`

**Objectifs**

- attaque `shomen uchi`
- déplacements sur uchi kaiten nage
  - katate dori
  - shomen uchi

**Pratique**

- [x] **salut et échauffement**

- [x] **courir en rond : un peu de cardio**

::: {.callout-tip title="cardio" collapse="true"}
courir en rond : 

- changements de direction
- flexion au "top" : x1 x2 x3
- pas chassés : intérieurs puis extérieurs
- talons-fesses
- marcher tranquillement
- shin kokyū
:::

- [ ] **henka / tenkan / tai sabaki**

- [x] **apprentissage de la chute arrière & chute avant (tapis & tatamis)**

- [x] **qu'a-t-on fait mercredi dernier ?**

::: {.callout-tip title="rappel" collapse="true"}
attaque shomen uchi

- sokumen irimi nage
- soto kaiten nage
:::

- [x] **Faire ces 2 techniques, deux fois**

- [x] _**Attaque `katate dori`**_ / **uchi kaiten nage**

::: {.callout-tip title="consignes" collapse="true"}
- uke attaque en `katate dori`
- tori se décale vers l'extérieur en montant le bras de uke
- tori fait un léger `atemi` sur le visage de uke et passe sous son bras (`iremi`)
- tori fait `henka+` en gardant bien le contrôle de la main de uke
- tori, en parallèle
  - descend très bas le bras de uke vers l'avant, retire le bras vers l'arrière et prend son poignet
  - pose sa main te-gatana sur le cou de uke et appuie pour le faire descendre
- tori engage sa jambre arrière et lève le bras de uke (cercle)
- uke fait une chute avant
:::

- [x] _**Attaque `Shomen Uchi`**_ / **uchi kaiten nage**

::: {.callout-tip title="consignes" collapse="true"}
- uke attaque en `shomen`
- tori lève son bras de devant en protection
- tori fait tai sabaki à l'extérieur en laissant descendre le bras de uke
- tori, parallèle à uke, récupère le poignet de uke avec la main la plus proche (pas celle du contrôle)
  - uke suit pour se retrouver devant tori (position katate dori, avec saisie par tori)
- tori se décale vers l'extérieur en montant le bras de uke
- tori fait un léger atemi sur le visage de uke et passe sous son bras (iremi)
- tori fait henka+ en gardant bien le contrôle de la main de uke
- tori, en parallèle
  - descend très bas le bras de uke vers l'avant, tire le bras vers l'arrière et prend son poignet
  - pose sa main te-gatana sur le cou de uke et appuie pour le faire descendre
- tori engage sa jambre arrière et lève le bras de uke (cercle)
- uke fait une chute avant
:::

- [x] **Jyu waza sur shomen uchi** 

::: {.callout-tip title="consignes" collapse="true"}
- les techniques vues
- changer toutes les 4 techniques
:::

- [ ] **kokyu ho | étirements | respiration | relaxation**

- [x] **salut**

{{< pagebreak >}}

## `[2024-12-11]`

**Objectifs**

- révision 1^er^trimestre
  - katate dori

**Pratique**

- [x] **salut et échauffement**

- [ ] **courir en rond : un peu de cardio**

::: {.callout-tip title="cardio" collapse="true"}
courir en rond : 

- changements de direction
- flexion au "top" : x1 x2 x3
- pas chassés : intérieurs puis extérieurs
- talons-fesses
- marcher tranquillement
- shin kokyū
:::

- [x] **henka / tenkan / tai sabaki**

- [x] **apprentissage de la chute arrière & chute avant (tapis & tatamis)**

_**Saisie Katate Dori**_

- [x] **kokyu nage** (avec tenkan)
- [x] **kokyu nage** (uchi kaiten)
- [x] **tenchi nage**
- [x] **sokumen irimi nage**
- [x] **shiho nage** omote & ura

- [ ] **Jyu waza sur katate dori** 

- [ ] **kokyu ho | étirements | respiration | relaxation**

- [x] **salut**

{{< pagebreak >}}

## `[2024-12-18]`

**Objectifs**

- révision 1^er^trimestre
  - Ai Hanmi Katate Dori
  - Shomen uchi

**Pratique**

- [x] **salut**
- [x] **taiso**
- [x] **cardio**

::: {.callout-tip title="cardio" collapse="true"}
courir en rond : 

- changements de direction
- flexion au "top" : x1 x2 x3
- pas chassés : intérieurs puis extérieurs
- talons-fesses
- marcher tranquillement
- shin kokyū
:::

- [x] **henka / tenkan / tai sabaki**
- [x] **apprentissage de la chute arrière & chute avant (tapis & tatamis)**

---

_**Saisie Ai Hanmi Katate Dori**_

- [x] **Ikkyo** omote & ura
- [x] **Irimi nage**

_**Attaque Shomen Uchi**_

- [x] **Ikkyo** omote & ura
- [x] **Irimi nage**

_**Saisie Ai Hanmi Katate Dori**_

- [x] **shiho nage** omote & ura
- [x] **Jyu waza sur ai hamni katate dori** 

_**Attaque Shomen Uchi**_

- [x] **Jyu waza sur shomen uchi** 

---

- [ ] **kokyu ho | étirements | respiration | relaxation**
- [x] **salut**

