# Octobre 2024 {.unnumbered}

## `[2024-10-02]`

**Objectifs**

- placement en Ai hanmi katate dori
- ura
- centrage (sur shiho nage ura)

**Pratique**

- [x] salut et échauffement
- [x] courir en rond : un peu de cardio

::: {.callout-tip title="cardio" collapse="true"}
- changements de direction
- flexion au "top"
- marche à quatre pattes
- marcher tranquillement
:::

- [x] apprentissage de la chute arrière & chute avant (tapis)
- [x] qu'a-t-on fait mercredi dernier et/ou samedi dernier ?

::: {.callout-tip title="rappel" collapse="true"}
- Ai Hanmi Katate Dori
  - ikkyo omote
  - irimi nage
:::

_**Saisie Ai Hanmi Katate Dori**_

- [x] **irimi nage** - consolidation

::: {.callout-tip title="consignes" collapse="true"}
- tori présente sa main, pouce en bas
- tori lève le bras de uke pour se faire le passage
- tori déplace loin sa jambe arrière vers l'extérieur
  - il se retrouve au niveau des épaules de uke
- tori fait henka en saisissant la tête de uke et en la posant sur l'épaule
- tori fait un pas chassé en laissant tomber le bras
- uke fait une chute arrière
:::

- [x] **ikkyo ura**

::: {.callout-tip title="consignes" collapse="true"}
- tori présente sa main, pouce en bas
- tori lève le bras de uke pour se faire le passage et saisit le coude
- tori déplace loin sa jambe arrière vers l'extérieur
  - il se retrouve au niveau des épaules de uke
- tori fait tenkan
- tori descend en spirale 
- même fin que pour omote
:::

- [x] **shiho nage ura**

::: {.callout-tip title="consignes" collapse="true"}
- tori présente sa main, paume vers le haut
- tori fait une rotation du poignet pour être en appui sur celui de uke
- tori saisit, avec sa main libre, le poignet de uke
- tori fait irimi puis tenkan
- tori monte ses poignets au dessus de sa tête
- tori fait henka
- tori descend ses mains vers son pied avant
- uke fait une chute arrière
:::

- [x] kokyu ho | étirements | respiration | relaxation

- [x] salut

**Présents** : Loup-Gaspard, Paul, Souheil, Iban, Mathis

{{< pagebreak >}}

## `[2024-10-09]`

**Objectifs**

- consolidation katate dori (avant les vacances)

**Pratique**

- [ ] **salut**
- [ ] **échauffement**
- [ ] **cardio**

::: {.callout-tip title="consignes" collapse="true"}
courir en rond : 

- changements de direction
- flexion au "top" : x1 X2 x3
- pas chassés : intérieurs puis extérieurs
- talons-fesses
- marcher tranquillement
- shin kokyū
:::

- [ ] **apprentissage de la chute arrière & chute avant (tapis)**
- [ ] **henka / tenkan / tai sabaki**
- [ ] **qu'a-t-on fait depuis le début de la saison en katate dori ?**

::: {.callout-tip title="rappel" collapse="true"}
- kokyu nage (sortie extérieure et main dans le coude)
- tenchi nage
- sokomen irimi nage
- shiho nage omote / ura
- kokyu nage (uchi kaiten)
:::

_**Saisie Katate Dori**_

- [ ] **kokyu nage** - révision

::: {.callout-tip title="consignes" collapse="true"}
les deux formes
:::

- [ ] **tenchi nage**
- [ ] **sokomen irimi nage**
- [ ] **shiho nage omote / ura**
- [ ] **retour au calme**
  - kokyu ho | étirements | respiration | relaxation
- [ ] **salut**

**Présents** : ...

{{< pagebreak >}}
