# Mai 2025 {.unnumbered}

## `[2025-05-07]`

**Objectifs**

- catalogue 5^ème^ kyu

**Pratique**

- [x] **salut et échauffement**
- [ ] **courir en rond : un peu de cardio**

::: {.callout-tip title="cardio" collapse="true"}
courir en rond : 

- changements de direction
- flexion au "top" : x1 x2 x3
- pas chassés : intérieurs puis extérieurs
- talons-fesses
- marcher tranquillement
- shin kokyū
:::

- [ ] **henka / tenkan / tai sabaki**
- [x] **apprentissage de la chute arrière & chute avant (tapis & tatamis)**

---

- [x] **`Shikko`**

- [x] **Attaque `Ai Hanmi Katate Dori / ikkyo omote & ura`**
- [x] **Attaque `Ai Hanmi Katate Dori / irimi nage`**
- [x] **Attaque `Ai Hanmi Katate Dori / shiho nage`**

- [ ] **Attaque `Shomen Uchi / ikkyo omote & ura`**
- [ ] **Attaque `Shomen Uchi / irimi nage`**

- [ ] **Attaque `Katate Dori / shiho nage`**
- [ ] **Attaque `Katate Dori / tenchi nahe`**

---

- [x] **kokyu hō**
- [x] **salut**

## `[2025-05-14]`

**Objectifs**

- catalogue 5^ème^ kyu (suite)

**Pratique**

- [x] **salut et échauffement**
- [ ] **courir en rond : un peu de cardio**

::: {.callout-tip title="cardio" collapse="true"}
courir en rond : 

- changements de direction
- flexion au "top" : x1 x2 x3
- pas chassés : intérieurs puis extérieurs
- talons-fesses
- marcher tranquillement
- shin kokyū
:::

- [x] **henka / tenkan / tai sabaki**
- [x] **apprentissage de la chute arrière & chute avant (tapis & tatamis)**

---

- [ ] **`Shikko`**

- [x] **Attaque `Ai Hanmi Katate Dori / ikkyo omote & ura`**
- [x] **Attaque `Ai Hanmi Katate Dori / irimi nage`**
- [x] **Attaque `Ai Hanmi Katate Dori / shiho nage`**

- [x] **Attaque `Shomen Uchi / ikkyo omote & ura`**
- [x] **Attaque `Shomen Uchi / irimi nage`**

- [x] **Attaque `Katate Dori / shiho nage`**
- [x] **Attaque `Katate Dori / tenchi nahe`**

---

- [x] **kokyu hō**
- [x] **salut**

## `[2025-05-21]`

**Objectifs**

- catalogue 4^ème^ kyu 

**Pratique**

- [x] **salut et échauffement**
- [ ] **courir en rond : un peu de cardio**

::: {.callout-tip title="cardio" collapse="true"}
courir en rond : 

- changements de direction
- flexion au "top" : x1 x2 x3
- pas chassés : intérieurs puis extérieurs
- talons-fesses
- marcher tranquillement
- shin kokyū
:::

- [x] **henka / tenkan / tai sabaki**
- [x] **apprentissage de la chute arrière & chute avant (tapis & tatamis)**

---

- [ ] **`Shikko`**

- [x] **Attaque `Ai Hanmi Katate Dori / kote gaeshi`**
- [x] **Attaque `Ai Hanmi Katate Dori / ude kime nage`**

- [x] **Attaque `Katate Dori / ikkyo omote & ura`**
- [x] **Attaque `Katate Dori / ude kime nage`**
- [ ] **Attaque `Katate Dori / sokumen irimi nage`**

---

- [ ] **kokyu hō**
- [ ] **salut**

{{< pagebreak >}}

## `[2025-05-28]`

**Objectifs**

- catalogue 4^ème^ kyu 

**Pratique**

- [x] **salut et échauffement**
- [ ] **courir en rond : un peu de cardio**

::: {.callout-tip title="cardio" collapse="true"}
courir en rond : 

- changements de direction
- flexion au "top" : x1 x2 x3
- pas chassés : intérieurs puis extérieurs
- talons-fesses
- marcher tranquillement
- shin kokyū
:::

- [x] **henka / tenkan / tai sabaki**
- [x] **apprentissage de la chute arrière & chute avant (tapis & tatamis)**

---

- [ ] **`Shikko`**

- [x] **Attaque `Katate Dori / sokumen irimi nage`**
- [x] **Attaque `Katate Dori / uchi kaiten nage`**

- [x] **Attaque `Shomen Uchi / kote gaeshi`**

- [x] **Attaque `Ryote Dori / tenchi nage`**

---

- [ ] **kokyu hō**
- [x] **salut**
