---
title: "Tableau de Bord Cours Enfants (saison 2024-2025)"
date:   today
date-format: "YYYY-MM-DD"
format: 
  dashboard:
    orientation: columns
    theme: 
      light: cerulean
      dark: darkly
logo: images/AAB_2020_logo_carre_fanion.png
logo-alt: "Aviron Bayonnais section Aïkido."
---

```{r}
#| label: load-packages
library(tidyverse)
library(gt)
library(scales)
library(knitr)
```

```{r}
#| label: load-data
# Les données sont sous NextCloud accessibles via WebDAV (synchro)
df_nc <- read.csv("/home/alain/Nextcloud_abret/Documents/Data/Cours_Enfants_Présences.csv")
```

```{r}
#| label: prep-data

df_cours <- df_nc[,1:4] |>
  dplyr::mutate(DateText=Date) |>
  dplyr::mutate(Date = as.Date(Date, format="%Y-%m-%d")) |>
  dplyr::mutate(Mois = factor(format(Date, "%Y-%m"))) |>
  dplyr::mutate(Enseignant = factor(Enseignant)) |>
  dplyr::rename(Pratiquants = Total.cours) |>
  dplyr::mutate(Jour = factor(Jour , levels=c("samedi","mercredi")))
```

# Graphiques

## Column - fréquentation {width=60%}

### Fréquentation par cours

```{r}
#| label: frequentation-cours
#| title: Fréquentation par cours

graph1 <- ggplot(data = df_cours, aes(x = DateText, y = Pratiquants, group = 1)) +
  geom_point(aes(colour = Enseignant)) +
  geom_line(color="skyblue") +
  theme(axis.text.x=element_text(angle=90, hjust=1)) +
  ylim(0, max(df_cours$Pratiquants) + 1) +
  xlab("Jour") 
plotly::ggplotly(graph1)
``` 

###  Fréquentation par mois {height=50% .tabset}

::: {.card title="Mois"}

```{r}
#| label: frequentation-boxplot-mois

graph2 <- ggplot(data = df_cours, aes(x = Mois, y = Pratiquants)) +
  geom_boxplot(fill = "skyblue") +
  stat_summary(fun="mean", geom="point", colour = "lightsteelblue4", shape=19, size = 2) + 
  theme(axis.text.x=element_text(angle=30, hjust=1), legend.position = "none") +
  xlab(NULL) +
  ylim(0, max(df_cours$Pratiquants) + 1) +
  ggtitle("Distribution de la fréquentation par mois")

plotly::ggplotly(graph2)
``` 
:::

::: {.card title="Mois et jour"}

```{r}
#| label: frequentation-boxplot-mois-sm

graph3 <- ggplot(data = df_cours, aes(x = Mois, y = Pratiquants)) +
  geom_boxplot(fill = "skyblue") +
#  facet_grid(cols = vars(Jour)) +
  facet_wrap(~ Jour) +
  stat_summary(fun="mean", geom="point", colour = "lightsteelblue4", shape=19, size = 2) + 
  theme(axis.text.x=element_text(angle=30, hjust=1), legend.position = "none") +
  xlab(NULL) +
  ylim(0, max(df_cours$Pratiquants) + 1) +
  ggtitle("Distribution de la fréquentation par mois et jour")

plotly::ggplotly(graph3)

``` 
:::

## Column - Présences {width=30%}

```{r}
#| label: presence
#| title: Présence aux cours

df_presences <- df_nc[,5:ncol(df_nc)]
df_presences[is.na(df_presences)] <- 0
presences <- sort(colSums(df_presences), decreasing = TRUE)
tab_presences <- as.data.frame(presences)
names(tab_presences)<- c("Cours")
tab_presences <- data.frame(Pratiquant=names(presences), tab_presences)
gt(tab_presences)

``` 

::: {.card title="Analyse"}
Mise à jour : `{r} Sys.Date()`

{{< include _analyse.md >}}
:::

# Statistiques

## Column - fréquentation {width=50%}

### {height="20%"}

```{r}
#| label: frequentation-cours-stats
#| title: Fréquentation par cours
#| 
table_summary_cours <- df_cours |>
    dplyr::summarise(
        cours=n(),
        min=round(min(Pratiquants, na.rm=T), 2),
        Q1=round(quantile(Pratiquants, 0.25, na.rm=T), 2),
        médiane=round(median(Pratiquants, na.rm=T), 2),
        moyenne=round(mean(Pratiquants, na.rm=T), 2),
        Q3=round(quantile(Pratiquants, 0.75, na.rm=T), 2),
        max=round(max(Pratiquants, na.rm=T), 2))
knitr::kable(table_summary_cours)
```

### {height="35%"}

```{r}
#| label: frequentation-cours-mois
#| title: Fréquentation par mois

table_summary_cours_mois <- df_cours |>
    dplyr::group_by(Mois) |>
    dplyr::summarise(
        cours=n(),
        min=round(min(Pratiquants, na.rm=T), 2),
        Q1=round(quantile(Pratiquants, 0.25, na.rm=T), 2),
        médiane=round(median(Pratiquants, na.rm=T), 2),
        moyenne=round(mean(Pratiquants, na.rm=T), 2),
        Q3=round(quantile(Pratiquants, 0.75, na.rm=T), 2),
        max=round(max(Pratiquants, na.rm=T), 2))
knitr::kable(table_summary_cours_mois)
```

### {height="35%"}

```{r}
#| label: frequentation-cours-mois-jour
#| title: Fréquentation par mois et jour

table_summary_cours_jour <- df_cours |>
    dplyr::group_by(Mois, Jour) |>
    dplyr::summarise(
        cours=n(),
        min=round(min(Pratiquants, na.rm=T), 2),
        Q1=round(quantile(Pratiquants, 0.25, na.rm=T), 2),
        médiane=round(median(Pratiquants, na.rm=T), 2),
        moyenne=round(mean(Pratiquants, na.rm=T), 2),
        Q3=round(quantile(Pratiquants, 0.75, na.rm=T), 2),
        max=round(max(Pratiquants, na.rm=T), 2))
knitr::kable(table_summary_cours_jour)
```
